version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-circuit-breaker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13dpon24syi2n"
s3_prefix = "serverless-circuit-breaker"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
