AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless Circuit Breaker for Lambda functions
  
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x

Parameters:
  SuccessThreshold: 
    Default: 2
    Description: Number of success executions before close the circuit breaker
    Type: Number
    MinValue: 1
    MaxValue: 100
  FailureThreshold: 
    Default: 3
    Description: Number of failure executions before open the circuit breaker
    Type: Number
    MinValue: 1
    MaxValue: 100
  CircuitBreakerTimeout: 
    Default: 20000
    Description: Time until attempt to close the circuit once it's open
    Type: Number
    MinValue: 1
    MaxValue: 60000

Resources:
##########################################################################
#   HTTP API                                                             #
##########################################################################
  PaymentsHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: definitions/api.yaml

##########################################################################
#  State Machine                                                         #
##########################################################################
  CircuitBreakerStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/circuit-breaker.asl.json
      Tracing:
        Enabled: true
      DefinitionSubstitutions:
        DefaultFunctionName: !Ref DefaultFunction
        FallbackFunctionName: !Ref FallbackFunction
        CircuitBreakersTable: !Ref CircuitBreakersTable
        OpenCircuitBreakerFunctionName: !Ref OpenCircuitBreaker
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref DefaultFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FallbackFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref OpenCircuitBreaker
        - DynamoDBCrudPolicy:
            TableName: !Ref CircuitBreakersTable
      Type: EXPRESS

##########################################################################
#  Lambda functions                                                      #
##########################################################################
  DefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: make-payment.handler

  FallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: make-payment-fallback.handler

  FillCircuitBreaker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/infrastructure/
      Handler: fill-circuit-breaker.handler
      Environment:
        Variables:
          CIRCUIT_BREAKER_TABLE_NAME: !Ref CircuitBreakersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CircuitBreakersTable
  
  OpenCircuitBreaker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/infrastructure/
      Handler: open-circuit-breaker.handler
      Environment:
        Variables:
          CIRCUIT_BREAKER_TABLE_NAME: !Ref CircuitBreakersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CircuitBreakersTable


##########################################################################
#   Tables                                                               #
##########################################################################
  CircuitBreakersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub CircuitBreakers
      
##########################################################################
#   Roles                                                                #
##########################################################################
  HttpApiRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
      - PolicyName: AllowSFNExec
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "states:StartSyncExecution"
              Resource: !GetAtt CircuitBreakerStateMachine.Arn
##########################################################################
#   Custom Resources                                                     #
##########################################################################
  CircuitBreaker:
    Type: 'Custom::CircuitBreaker'
    DependsOn: ['CircuitBreakersTable', 'FillCircuitBreaker']
    Version: '1.0'
    Properties:
      DefaultFunction: !Ref DefaultFunction
      FallbackFunction: !Ref FallbackFunction
      SuccessThreshold: !Ref SuccessThreshold
      FailureThreshold: !Ref FailureThreshold
      CircuitBreakerTimeout: !Ref CircuitBreakerTimeout
      ServiceToken: !GetAtt 'FillCircuitBreaker.Arn'

##########################################################################
#   Outputs                                                              #
##########################################################################
Outputs:
  PaymentApi:
    Description: "API Gateway endpoint URL for Prod stage for Payments API"
    Value: !Sub "https://${PaymentsHttpApi}.execute-api.${AWS::Region}.amazonaws.com/payment"
  DefaultFunction:
    Description: "Default function ARN"
    Value: !GetAtt DefaultFunction.Arn
  FallbackFunction:
    Description: "Fallback function ARN"
    Value: !GetAtt FallbackFunction.Arn
